#!/usr/bin/env ruby

require "erb"

if ARGV.length < 3
  puts <<-USAGE
#$0 template_file choices_file number_of_boards
  USAGE
  exit
end

template = File.read(ARGV[0])
choices = File.read(ARGV[1]).split("\n")
number_of_boards = ARGV[2].to_i

boards = Array.new(number_of_boards) {
  choices.shuffle.take(24)
}

puts ERB.new(template).result(binding)
